### ISSUE TITLE
[Android 11] Contact Sync apk not working

### ISSUE THREAD

**Issue by juliazero** [Psk-Ita/microG-GApps#6]
After install module and reboot, contacts sync apk is not installed (calendar is installed)

I tried to install apk from /system/priv-app, but I get:
"There is a problem parsing the package"

Apk is to new for android 11.
Tested on crdroid 7
Working on AEX android 12.

**Comment by Psk-Ita** [comment]
You can see in folder tree "/system/priv-app" contains "GoogleCalendarSyncAdapter" and "GoogleContactsSyncAdapter" I extracted those from GApps I was using (on android 12)
you can do the same:
download the smaller gapps asset for you android version, check in the nested zip, and replace the "GoogleContactsSyncAdapter" apk loaded from GApps package and replace the one extracted in
"/data/adb/modules/microG-GApps//system/priv-app/GoogleContactsSyncAdapter" folder
at the next restart it will start working propertly
